version: '2'
services:
    vtravel-app:
        image: vtravel
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://vtravel-mysql:3306/vtravel?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=vtravel-elasticsearch:9300
        ports:
            - 8080:8080
    vtravel-mysql:
        extends:
            file: mysql.yml
            service: vtravel-mysql
    vtravel-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: vtravel-elasticsearch
